version: '3.8'

services:
  main:
    container_name: nest-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${APP_PORT:-4000}:${APP_PORT:-4000}
    depends_on:
      - postgres
    env_file:
      - .env

  postgres:
    container_name: postgres
    image: postgres:13
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT:-5432}:${POSTGRES_PORT:-5432}
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: always
    command: -p ${POSTGRES_PORT:-5432}

volumes:
  postgres:
    name: nest-db
    external: true